USE_CAMERA_STUB := false

TARGET_SPECIFIC_HEADER_PATH := device/huawei/G300/include
TARGET_OTA_ASSERT_DEVICE := G300,U8815,u8815,hwu8815

#Board Settings
TARGET_ARCH:= arm
TARGET_NO_BOOTLOADER := true
TARGET_NO_RADIOIMAGE := true
TARGET_BOARD_PLATFORM := msm7x27a
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_BOOTLOADER_BOARD_NAME := G300
TARGET_ARCH_VARIANT := armv7-a-neon
ARCH_ARM_HAVE_TLS_REGISTER := true
TARGET_GLOBAL_CFLAGS += -mtune=cortex-a5 -mfpu=neon -mfloat-abi=softfp -march=armv7-a 
TARGET_GLOBAL_CPPFLAGS += -mtune=cortex-a5 -mfpu=neon -mfloat-abi=softfp -march=armv7-a
TARGET_BOARD_PLATFORM_GPU := qcom-adreno200
BOARD_USES_ADRENO_200 := true
#TARGET_PROVIDES_INIT := true
#BOARD_USE_NO_DEVFS_SETUP := true
TARGET_PROVIDES_INIT_RC := true
TARGET_PROVIDES_RECOVERY_INIT_RC := true
TARGET_RECOVERY_INITRC := device/huawei/G300/init.rc
TARGET_CPU_SMP := true
TARGET_ARCH_VARIANT_CPU := cortex-a5
SMALLER_FONT_FOOTPRINT := true
MINIMAL_FONT_FOOTPRINT := true
ARCH_ARM_HIGH_OPTIMIZATION := true
TARGET_ARCH_VARIANT_FPU := neon
TARGET_CORTEX_CACHE_LINE_32 := true
#BOARD_USES_SRS_TRUEMEDIA := true 
 

# QCOM hardware
BOARD_USES_QCOM_HARDWARE := true
COMMON_GLOBAL_CFLAGS += -DQCOM_HARDWARE

   WEBCORE_INPAGE_VIDEO := true
TARGET_HAVE_TSLIB := false

# Camera
COMMON_GLOBAL_CFLAGS += -DICS_CAMERA_BLOB
BOARD_NEEDS_MEMORYHEAPPMEM := true
BOARD_USES_QCOM_LEGACY_CAM_PARAMS := true

#Graphics
BOARD_EGL_CFG := device/huawei/G300/proprietary/lib/egl/egl.cfg
USE_OPENGL_RENDERER := true
COMMON_GLOBAL_CFLAGS += -DFORCE_CPU_UPLOAD 
COMMON_GLOBAL_CFLAGS += -DQCOM_NO_SECURE_PLAYBACK -DREFRESH_RATE=65 -DQCOM_LEGACY_OMX -DQCOM_ICS_DECODERS -DANCIENT_GL
COMMON_GLOBAL_CFLAGS += -DPOLL_CALL_STATE -DUSE_QMI 
TARGET_USES_GENLOCK := true
TARGET_USES_SF_BYPASS := false
TARGET_HAVE_BYPASS := false
TARGET_USES_OVERLAY := false
TARGET_GRALLOC_USES_ASHMEM := true
BOARD_USE_SKIA_LCDTEXT := true
BOARD_AVOID_DRAW_TEXTURE_EXTENSION := true
TARGET_USES_16BPPSURFACE_FOR_OPAQUE := true
BOARD_ADRENO_DECIDE_TEXTURE_TARGET := true
TARGET_NO_HW_OVERLAY := true
TARGET_QCOM_DISPLAY_VARIANT := legacy
TARGET_QCOM_MEDIA_VARIANT := legacy


#Browser
ENABLE_WEBGL := true
TARGET_FORCE_CPU_UPLOAD := true
WITH_JIT := true
ENABLE_JSC_JIT := true
JS_ENGINE := v8
BOARD_USE_QCOM_LLVM_CLANG_RS := true

#GPS
BOARD_USES_QCOM_LIBS := true
BOARD_USES_QCOM_LIBRPC := true
BOARD_USES_QCOM_GPS := true
BOARD_VENDOR_QCOM_GPS_LOC_API_AMSS_VERSION := 50000
BOARD_VENDOR_QCOM_GPS_LOC_API_HARDWARE := default

# Audio
BOARD_HAVE_QCOM_FM := true
COMMON_GLOBAL_CFLAGS += -DWITH_QCOM_FM -DQCOM_FM_ENABLED -DQCOM_VOIP_ENABLED 
TARGET_PROVIDES_LIBAUDIO := true


# Wi-Fi
BOARD_HAVE_HUAWEI_WIFI := true
WPA_SUPPLICANT_VERSION      := VER_0_8_X
BOARD_WPA_SUPPLICANT_DRIVER := NL80211
BOARD_WLAN_DEVICE           := bcmdhd
WIFI_DRIVER_MODULE_PATH     := "/system/lib/modules/dhd_4330.ko"
BOARD_WPA_SUPPLICANT_PRIVATE_LIB := lib_driver_cmd_bcmdhd
BOARD_HOSTAPD_DRIVER        := NL80211
BOARD_HOSTAPD_PRIVATE_LIB   := lib_driver_cmd_bcmdhd
WIFI_DRIVER_MODULE_NAME := "dhd_4330"
BOARD_LEGACY_NL80211_STA_EVENTS := true
WIFI_DRIVER_FW_PATH_STA := "/system/wifi/fw_4330_b2.bin"
WIFI_DRIVER_FW_PATH_P2P := "/system/wifi/fw_4330_b2_p2p.bin"
WIFI_DRIVER_FW_PATH_AP := "/system/wifi/fw_4330_b2_apsta.bin"
WIFI_DRIVER_FW_PATH_PARAM := "/sys/module/dhd_4330/parameters/firmware_path"
WIFI_DRIVER_MODULE_ARG := "firmware_path=/system/wifi/fw_4330_b2.bin nvram_path=/system/wifi/nvram_4330.txt"
WIFI_BAND                        := 802_11_ABG

PRODUCT_WIRELESS_TOOLS := true

# Bluetooth
BOARD_HAVE_BLUETOOTH := true
BOARD_HAVE_BLUETOOTH_BCM := true
BOARD_BLUETOOTH_BDROID_BUILDCFG_INCLUDE_DIR := device/huawei/G300/bluetooth
BOARD_BLUEDROID_VENDOR_CONF := device/huawei/G300/bluetooth/vnd_g300.txt


#RIL
BOARD_RIL_CLASS := HuaweiRIL2


#Sensors
TARGET_PROVIDES_LIBLIGHT :=true


# Bootanimation
TARGET_BOOTANIMATION_PRELOAD := true

#kernel
BOARD_KERNEL_CMDLINE := androidboot.hardware=huawei
BOARD_KERNEL_BASE := 0x00200000
BOARD_PAGE_SIZE := 2048
TARGET_KERNEL_SOURCE := kernel/huawei/kernel
TARGET_KERNEL_CONFIG := g300_jb_defconfig


# Partitions
BOARD_USES_MMCUTILS := true

BOARD_BOOTIMAGE_PARTITION_SIZE := 0x00C00000
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 0x00C00000
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 536870912
BOARD_USERDATAIMAGE_PARTITION_SIZE := 1073741824
BOARD_FLASH_BLOCK_SIZE := 131072
TARGET_USERIMAGES_USE_EXT4 := true

BOARD_HAS_NO_MISC_PARTITION := true


# Use this flag if the board has a ext4 partition larger than 2gb
BOARD_HAS_LARGE_FILESYSTEM := true

# SD Card
BOARD_HAS_SDCARD_INTERNAL := true
BOARD_SDEXT_DEVICE := /dev/block/mmcblk1p1
BOARD_USES_MMCUTILS := true

# Insecure boot
ADDITIONAL_DEFAULT_PROPERTIES += ro.secure=0
ADDITIONAL_DEFAULT_PROPERTIES += persist.service.adb.enable=1


BOARD_VOLD_MAX_PARTITIONS :=30
TARGET_USE_CUSTOM_LUN_FILE_PATH := "/sys/class/android_usb/android0/f_mass_storage/lun%d/file"
BOARD_UMS_LUNFILE := "/sys/class/android_usb/android0/f_mass_storage/lun%d/file"
BOARD_VOLD_EMMC_SHARES_DEV_MAJOR := true
BOARD_VOLD_DISC_HAS_MULTIPLE_MAJORS := true

BOARD_HAS_NO_SELECT_BUTTON := true
TARGET_RECOVERY_PIXEL_FORMAT := "RGBX_8888"
TARGET_RECOVERY_GUI := true
DEVICE_RESOLUTION := 480x800
TW_INTERNAL_STORAGE_PATH := "/sdcard"
TW_INTERNAL_STORAGE_MOUNT_POINT := "sdcard"
TW_EXTERNAL_STORAGE_PATH := "/sdcard-ext"
TW_EXTERNAL_STORAGE_MOUNT_POINT := "sdcard-ext"
TW_FLASH_FROM_STORAGE := true 

SP1_NAME := "cust"
SP1_DISPLAY_NAME := "cust"
SP1_BACKUP_METHOD := image
SP1_MOUNTABLE := 1
SP2_NAME := "sdcard"
SP2_BACKUP_METHOD := files
SP2_MOUNTABLE := 1
